version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  commands:
    - git clone --depth=1 https://github.com/flutter/flutter.git -b stable
    - export FLUTTER_PATH=`pwd`/flutter/bin
    - $FLUTTER_PATH/flutter doctor -v
    - $FLUTTER_PATH/flutter pub get
    - $FLUTTER_PATH/dart doc .
    - mv doc/api _build/html

sphinx:
  configuration: doc/api/index.html

formats:
  - htmlzip