version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  commands:
    - git clone --depth=1 https://github.com/flutter/flutter.git -b stable
    - flutter/bin/flutter doctor -v
    - flutter/bin/flutter pub get
    - flutter/bin/dart doc .
    - mv doc/api _build/html

sphinx:
  configuration: doc/api/index.html

formats:
  - htmlzip